apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginserver
  labels:
    app: loginserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loginserver
  template:
    metadata:
      labels:
        app: loginserver
    spec:
      containers:
        - name: loginserver
          image: yklee2002/loginserver:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: loginserver-service
  labels:
    app: loginserver
spec:
  type: NodePort
  selector:
    app: loginserver
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30114

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: delivery-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/auth-url: "http://authserver.default.svc.cluster.local:8080/api/auth/validate"
    nginx.ingress.kubernetes.io/auth-method: "GET"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Authenticated-User"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /delivery(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: delivery-service
                port:
                  number: 80
